# Generated by Django 3.2.18 on 2023-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_resume_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.CharField(max_length=7),
        ),
    ]
